# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f827a92a5575ba839406fbd0a6360a88b92eb1ff06fcb0aa2010a0bc4eb0d9566158a336e1d4044733f3997d84e1b086305250ae67f1a8700d881b4a74ec8134

test:
  secret_key_base: 9ed08506970bbbd20f48c8f5742463e83e4aa6ae88871eadf81344e876698fb2c2623b6292989ba0df50627d302f4fd5b03e48d194e28154398d020cde5f5bb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
